server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

jwt:
  secret-key: a0df1b20ad4c7f202a9ebc50645ab57b584e247df9c4c939
  access-token-time: 1800000  # 30분
  refresh-token-time: 1209600000 # 14일